### PR TITLE
Move modules to new backend/frontend directories

### PR DESCRIPTION
**Pull request by tfuxu**
# Description

This is a yet another refactoring PR (I promise this will be the last _major_ one), this time I based it on a codebase structure used by Bottles project. The new structure should be more readable, and easier to navigate. Also, as a nice small bonus, I've included `struct.md` files inside `frontend/` and `backend/` directories with small descriptions for subdirectories.

## Type of change

- [x] Refactor
- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [ ] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Rename `utils/css.py` to `utils/css_parser.py` and `utils/custom_presets.py` to `utils/preset_downloader.py`,
- Move modules to new backend/frontend directories,
- Change module name from `utils.py` to `common.py`,
- Format some modules for better readability

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

Just check if everything is working as expected in every build method (I've tested this PR with manual and Flatpak methods)

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Wow, this will be hard review

**Comment by tfuxu** [comment]
> Wow, this will be hard to review

Yea I know, but that's the charm of my refactor PRs :^). I really hope this will be the last one, as now everything is neatly segregated into subdirectories

**Comment by daudix-UFO** [comment]
The one check that matters is if Gradience launches xD

**Comment by tfuxu** [comment]
True 😄️

**Review by daudix-UFO — APPROVED** [review]
It works, everything sorted nicely, just fantastic!

**Comment by tfuxu** [comment]
Great, let's get this merged then!

**Comment by daudix-UFO** [comment]
LFG! :rocket:

**Comment by 0xMRTT** [comment]
Okay, i'll add the cli

**Comment by tfuxu** [comment]
> Okay, i'll add the cli

What? You mean in shell theming PR, or as a standalone PR?

**Comment by 0xMRTT** [comment]
I mean to extract the cli from #632 and move it to a new PR

**Pull request merged**
