### PR TITLE
Rename the project to Gradience

### PR DESCRIPTION
**Pull request by AndroGR**
Basically a WIP of renaming this to Gradience. Feel free to fix the rest, I will finish in a week or so at most. GitHub links pending.

### CODE REVIEW

**Review by AdwCustomizer — COMMENTED** [review]
Welcome on Gradience. 🥳 We really appreciate your pull request. The core team will review your issue as soon as possible.

**Comment by AndroGR** [comment]
Very briefly explaining, this is
1. Unfinished work (I will pick up later a huge part on the domain names, eg. `com.github.AdwCustomizerTeam.AdwCustomizer`
2. Halted because the GitHub links are still using `AdwCustomizerTeam/x`

**Comment by daudix-UFO** [comment]
@0xMRTT, @AndroGR also changed code name, what we need to do with it?

**Comment by AndroGR** [comment]
@daudix-UFO Say again?

**Comment by daudix-UFO** [comment]
> Very briefly explaining, this is
> 
>     1. Unfinished work (I will pick up later a huge part on the domain names, eg. `com.github.AdwCustomizerTeam.AdwCustomizer`
> 
>     2. Halted because the GitHub links are still using `AdwCustomizerTeam/x`

AdwCustomizer is "under the hood" name, like nautilus in files, epiphany in GNOME Web and etc.

**Comment by AndroGR** [comment]
Exactly, I am change all the references to this to `com.github.GradienceTeam.Gradience`. Like I said, it's a wip.

**Comment by AndroGR** [comment]
I can add the domain name changes like discussed above in a few mins. Is that OK?

**Comment by daudix-UFO** [comment]
I not sure, need to discuss it with the team (in matrix maybe?)

**Comment by AndroGR** [comment]
I don't use matrix, I don't even know what that is to be honest, only brief mentions of it. But not to get out of the topic, the rest of the team can discuss it without me. Keep me updated on GitHub tho.

**Comment by daudix-UFO** [comment]
https://element.io/

**Comment by daudix-UFO** [comment]
> I don't use matrix, I don't even know what that is to be honest, only brief mentions of it. But not to get out of the topic, the rest of the team can discuss it without me. Keep me updated on GitHub tho.

I will ;)

**Comment by 0xMRTT** [comment]
Hi 👋 @AndroGR .

Thanks for taking part in the project.

For being more productive and don't miss any occurrence of the old name, I suggest using sourcegraph.

About the codename changement (AdwCustomizer to gradience), I think it's probably better to keep AdwCustomizer as codename and use Gradience as project name. Like nautilus and files or epiphany and Web.

Also, I suggest to create a matrix account on app.element.io, it's a messaging system very used in Foss projects. You can join the matrix room. See link on the README.

If you know python, I suggest you to help me doing the plugin system or when plugin system will be done, creating plugins. 

If you are good in web techs, you can improve the website (will be useful for storing the doc about plugins)

If you are good in ci, shell and automation. You can improve the flatpak build (currently locales are missing).

If you know a language other than English, you can translate Gradience

If you have any questions. Ask me !

I hope 🤞 it will be helpful.

**Comment by AndroGR** [comment]
> About the codename changement (AdwCustomizer to gradience), I think it's probably better to keep AdwCustomizer as codename and use Gradience as project name. Like nautilus and files or epiphany and Web.

Wasn't the whole point of changing the app name avoiding imitation of GNOME? Let's just change it all in once now instead of making it so complex for everybody.

That being said, not many parts indicating the "codename" have changed. I have a local commit ready that would do exactly that.

**Comment by 0xMRTT** [comment]
Need to reflect about this. 🙂

**Comment by daudix-UFO** [comment]
@AndroGR In Builder, you can find and replace any word just with one button

image

**Comment by 0xMRTT** [comment]
Hi @AndroGR 
After discussion, we choosed to move to the GradienceTeam org 👍🎉👋.

I sended an invitation.

**Comment by AndroGR** [comment]
@daudix-UFO Can I be invited on the matrix server in the meantime? My username is @androgr , kinda created it for the team so we can discuss more conveniently.

**Comment by daudix-UFO** [comment]
Just enter this room: https://matrix.to/#/#AdwCustomizer:matrix.org

**Comment by AndroGR** [comment]
Don't you think that also gives access to other arbitrary people on the server chat?

**Comment by daudix-UFO** [comment]
No

**Comment by daudix-UFO** [comment]
I am moder, if someone starts spamming, I will mute or ban him ;)

**Comment by 0xMRTT** [comment]
Me too 😉

**Comment by 0xMRTT** [comment]
I suggest you to work on the rebrand branch, you have access to push on. (Tell me if not)

**Comment by AndroGR** [comment]
I don't know if I left behind anything; I will change it later if that's the case.

**Comment by 0xMRTT** [comment]
There is a problem with actions (see @gitbubstatus)

**Comment by AndroGR** [comment]
I'm gonna merge it later then, kinda unlucky.

**Comment by 0xMRTT** [comment]
Did you tried to build?

**Comment by 0xMRTT** [comment]
Because why there is `>>>>>>>` added in files ?

**Pull request closed without merging**
