### PR TITLE
feat: add keyboard shortcuts (#776)

### LINKED ISSUE #776: feat: Add shortcuts
### Feature description

A shortcuts for opening preferences and displaying apply dialog would be nice to have, as well as help overlay

<kbd>Control</kbd> <kbd>,</kbd> - Open Preferences

<kbd>Control</kbd> <kbd>Return</kbd> - Show Apply Dialog

<kbd>Control</kbd> <kbd>?</kbd> - Show Help Overlay

<kbd>Alt</kbd> <kbd>1 - 3</kbd> - Switch Section

> изображение

### Additional Context

A shortcut for opening preset manager would be nice to have too, tho I'm not sure what shortcut is good for this

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by 0xMRTT**
## Description

image

Fixes #776 

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Added Help Overlay

## Testing

- [x] I have tested my changes and verified that they work as expected

### CODE REVIEW

**Review by daudix-UFO — APPROVED** [review]
Something that were missing and caused this feeling of that something is off, LGTM!

**Comment by 0xMRTT** [comment]
image

**Comment by 0xMRTT** [comment]
Now it should be Okay!

**Review by tfuxu — APPROVED** [review]
Great little addition to Gradience. LGTM

**Pull request merged**
