### PR TITLE
Fix #624, always save as User.json

### LINKED ISSUE #624: bug: Gradience always saves custom presets as "User.json".
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Like in the title, Gradience always saves custom presets as `User.json`, even though it announces to do otherwise. This breaks user experience because it's not possible to save a second preset without removing the previous one, even under a different name. The problem occurs in Gradience version 0.3.1-2 provided by package `gradience` from the Arch Linux User Repository.

### To Reproduce

1. Install `gradience` from the AUR.
2. Save a custom preset under a name "My Custom Preset".
3. Navigate to `~/.config/presets/user` just to find a single file named `User.json`.

### Expected behavior

It is expected for the file to be named `my-custom-preset.json`.

### Screenshots

Screenshot from 2022-10-10 22-06-52

### OS

Arch Linux

### Version

0.3.1-2

### Installation method

AUR

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 0xMRTT**

### CODE REVIEW

**Review by tfuxu — CHANGES_REQUESTED** [review]
Now it works almost as it should, the only bug left is the display name saved in slug case.

**Comment by daudix-UFO** [comment]
Also downloaded presets removal not working

**Comment by tfuxu** [comment]
> Also downloaded presets removal not working

Preset renames doesn't work too, but those bugs aren't related to changes in this PR.

**Review by daudix-UFO — COMMENTED** [review]
It working but it changes the name displayed in Preset Manager to lower-case

**Comment by tfuxu** [comment]
Fix (I don't have permissions to edit someone else's PR's, so this is the only way to add that fix here, I guess):
https://gist.github.com/tfuxu/409a700cff4cf064e52ce13682539b0b
this is a .patch file, so to apply this, you need to type: `git am <  0001-fix-Use-different-variables-for-display-name-and-fil.patch`

**Comment by daudix-UFO** [comment]
@0xMRTT Can you add this patch?

**Comment by 0xMRTT** [comment]
Yes, @daudix-UFO I think that we should give commit access to every major contributor and prioritize the usage of PR instead of just committing?

**Comment by daudix-UFO** [comment]
Fully agree!

**Comment by 0xMRTT** [comment]
@GradienceTeam/commit is the team for everyone with commit access on gradience repo

**Comment by daudix-UFO** [comment]
> @GradienceTeam/commit is the team for everyone with commit access on gradience repo

There is already core and members teams

**Comment by 0xMRTT** [comment]
Hmm

**Comment by 0xMRTT** [comment]
Hmm, i did a mess in when applied the patch, but rename and delete is working

**Comment by daudix-UFO** [comment]
Tested it RN, looks like it have some issues

Name was `Test WITH some-thing`

изображение

**Comment by tfuxu** [comment]
Now it should work

**Review by tfuxu — APPROVED** [review]

**Comment by 0xMRTT** [comment]
@daudix-UFO is it okay now ?

**Comment by daudix-UFO** [comment]
Yes, works perfectly fine now!

**Review by daudix-UFO — APPROVED** [review]

**Comment by 0xMRTT** [comment]
Team work :+1:

**Comment by daudix-UFO** [comment]
Sorry if you wanted to merge your PR 😅

**Comment by 0xMRTT** [comment]
No, that's great

**Pull request merged**
