### PR TITLE
build.yml: bump flatpak builder version

### PR DESCRIPTION
**Pull request by kbdharun**
## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

No information provided.

### CODE REVIEW

**Review by tfuxu — APPROVED** [review]
Looks good to me, but I'll wait with merging your PR until all build workflows are finished

**Comment by tfuxu** [comment]
I'm putting your PR as a draft for now, as I want to investigate why aarch64 builds are taking so long to build.

**Comment by daudix-UFO** [comment]
Maybe I'm wrong but aarch64 builds are always long the first time, then it uses cache and builds fast (the build runs in vm so it slower)

**Comment by 0xMRTT** [comment]
Yes 👍

**Comment by tfuxu** [comment]
This is probably the culprit of this issue: https://github.com/flatpak/flatpak-github-actions/commit/56ddaec9c3d543f3b3a7c81665fa806a51a811e9. From what I understand checking test CIs, a new action run (not a re-run) should have a different cache key, which should fix this issue. I'll merge this PR to check if this is true.

**Pull request merged**
