### PR TITLE
Add Swedish Translation

### PR DESCRIPTION
**Pull request by bittin**
Added Swedish Translation

### CODE REVIEW

**Review by AdwCustomizer — COMMENTED** [review]
Welcome on Gradience. 🥳 We really appreciate your pull request. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
Thanks :+1: 

If you want, you can use weblate

**Comment by bittin** [comment]
@0xMRTT ah alright, did not know the project was on Weblate good to know :)

**Comment by 0xMRTT** [comment]
See [`CONTRIBUTING.md`](https://github.com/GradienceTeam/Gradience/blob/main/CONTRIBUTING.md)

**Comment by bittin** [comment]
ah perfect thank you

**Pull request merged**
