### PR TITLE
feat: use switch ative instead of state

### PR DESCRIPTION
**Pull request by FineFindus**
## Description

Changes the [Switches](https://docs.gtk.org/gtk4/class.Switch.html) to use the `active` property, which controls both color and position, instead of `state`, which only changes the switch color.

It also sets the `activatable-widget` on the jsdeliver ActionRows allowing the user to click anywhere to activate the switch.

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Fixed a bug where Switches were not shown as active

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

1. Open the preferences
2. Notice how the switches have both the correct position and color

### CODE REVIEW

**Comment by daudix-UFO** [comment]
There are a bug with switches not saving their state (at least visually)

[Kooha-2023-06-26-23-22-10.webm](https://github.com/GradienceTeam/Gradience/assets/77155297/83e90cdd-516f-4f94-9828-87220f56b1b7)

**Comment by 0xMRTT** [comment]
In this pr or before ? Because I remember a that we had some issues with switch...

**Comment by 0xMRTT** [comment]
Hmm, I fixed it, pushed but it doesn't appear in this PR ... It appear in the branch `feat/switch-state` in the Gradience repo... Gonna close the PR and reopen

**Comment by 0xMRTT** [comment]
https://github.com/GradienceTeam/Gradience/pull/792

**Pull request closed without merging**
