### PR TITLE
docs: add usage documentation

### LINKED ISSUE #699: feat: Create user documentation
### Feature description

Not much to say here, we just need to create a user documentation to unclutter our repository README, and to give users more info on some features.

### Additional Context

_No response_

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by 0xMRTT**
# Description

> Not much to say here, we just need to create a user documentation to unclutter our repository README, and to give users more info on some features.

Fixes #699

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [x] New feature (Change which adds new functionality)
- [ ] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Added user guide

## Testing

- [x] I have tested my changes and verified that they work as expected

### CODE REVIEW

**Comment by 0xMRTT** [comment]
image
 
I choosed to use the RtD theme

**Comment by daudix-UFO** [comment]
Can I see other themes?

**Comment by 0xMRTT** [comment]
It's sphinx (https://www.sphinx-doc.org/) and the theme is one of the most used: Read The Docs Theme, you can just search for Sphinx theme online

**Comment by 0xMRTT** [comment]
So what do we want to include in the user doc ? 

- [ ] installation
- [ ] setup
- [ ] how to use gradience
- [ ] troubleshoot
- [ ] cli usage
- [ ] faq

**Comment by tfuxu** [comment]
@daudix-UFO 
You can check a pretty big curated list of Sphinx themes here: https://sphinx-themes.org/

**Comment by daudix-UFO** [comment]
I think we can change the theme later, so I will have time to look at them ;)

**Comment by daudix-UFO** [comment]
> * how to use gradience

Later when we will have website we can create a handbook, small set of guides and tips for gradience, docs will remain useful but as for new users it will be handy

**Comment by daudix-UFO** [comment]
After looking at all themes, I think that https://sphinx-themes.org/sample-sites/furo and https://sphinx-themes.org/sample-sites/sphinx-book-theme are looking pretty neat, I like the _furo_ the most, it also have dark mode

**Comment by 0xMRTT** [comment]
I really like fuel to BC of the dark mode. Gonna change

**Comment by tfuxu** [comment]
fuel? If you meant furo, then I also agree, although I think it will need a little tweaking later.

**Comment by daudix-UFO** [comment]
> although I think it will need a little bit of tweaking later

This would be very nice!

**Comment by tfuxu** [comment]
> it feels too "square", a bit of rounding will make it better

fr, true

**Comment by 0xMRTT** [comment]
image

**Comment by daudix-UFO** [comment]
@0xMRTT Looks dope!

**Comment by daudix-UFO** [comment]
Maybe [Inter](https://rsms.me/inter) font will look better?

_Also I have changed the sidebar logo_

Снимок экрана от 2023-02-10 14-43-53
Снимок экрана от 2023-02-10 15-16-11

**Comment by tfuxu** [comment]
Inter looks better from default, but we should also consider [Cantarell](https://cantarell.gnome.org), which we use on all our current websites.

**Comment by daudix-UFO** [comment]
First screenshot uses Cantarell

**Comment by tfuxu** [comment]
> First screenshot uses Cantarell :) (or at least it set to be cantarell)

Oh okay, then I would go with Cantarell, as the title looks more smooth and not as bold as on the first screenshot.

**Comment by daudix-UFO** [comment]
As Cantarell is not pre-installed on every system, maybe we should pack it with docs?

**Comment by tfuxu** [comment]
> As Cantarell is not pre-installed on every system, maybe we should pack it with docs?

Good idea

**Comment by daudix-UFO** [comment]
I think I have done this, the structure is like this

```
├── _static
│   ├── css
│   │   └── custom.css
│   └── fonts
│       ├── Cantarell-VF.otf
│       └── Cantarell-VF.woff2
```

**Comment by tfuxu** [comment]
Should be good, but you also need to import this font in CSS file.

**Comment by daudix-UFO** [comment]
CSS

```
/* FONTS */
@font-face {
  font-family: "Cantarell var";
  font-weight: 100 900;
  font-display: swap;
  font-style: normal;
  font-named-instance: "Regular";
  src: url("_static/fonts/Cantarell-VF.woff2") format("woff2"),
    url("_static/fonts/Cantarell-VF.otf") format("opentype");
}

html {
  font-family: "Cantarell", sans-serif;
}
```

HTML have a link to this css, as sphinx wiki says

https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by tfuxu** [comment]
> CSS
> 
> _From Cantarell [website](https://gitlab.gnome.org/Teams/Design/cantarell.gnome.org)_
> 
> ```
> /* FONTS */
> @font-face {
>   font-family: "Cantarell var";
>   font-weight: 100 900;
>   font-display: swap;
>   font-style: normal;
>   font-named-instance: "Regular";
>   src: url("_static/fonts/Cantarell-VF.woff2") format("woff2"),
>     url("_static/fonts/Cantarell-VF.otf") format("opentype");
> }
> 
> html {
>   font-family: "Cantarell", sans-serif;
> }
> ```

Yea, this should work.

> But for some reason font does not look like Cantarell on phone

It looks for me like a Cantarell, I see that looking for example on a upper comma.

**Comment by daudix-UFO** [comment]
But "l" in "Welcome" is different

**Comment by tfuxu** [comment]
Ah true, it has Inter font applied for some reason.

**Comment by daudix-UFO** [comment]
> Ah true, it has Inter font applied for some reason.

Or default fallback font

**Comment by tfuxu** [comment]
Nah, fallback looks different from both of them. Especially if you look at that upper comma.

**Comment by 0xMRTT** [comment]
@daudix-UFO could you push your changes ? Also, what docs are missing?

**Comment by tfuxu** [comment]
> Also, what docs are missing?

We should create an Troubleshooting section

**Comment by daudix-UFO** [comment]
> @daudix-UFO could you push your changes ? Also, what docs are missing?

Yep

**Comment by daudix-UFO** [comment]
I have fixed the fonts!

Screenshot_20230210-182558_Firefox

**Comment by daudix-UFO** [comment]
One thing I would like to see is:

```
image-rendering: -webkit-optimize-contrast; /* Chromium and Safari */
image-rendering: crisp-edges;
```

For the sidebar gif

**Comment by 0xMRTT** [comment]
@daudix-UFO while updating the AUR, i noticed that appstream check fail (not important but...)

```
3/3 Validate appstream file        FAIL            1.73s   exit status 1
>>> MALLOC_PERTURB_=80 /usr/bin/appstream-util validate /home/user/aur/gradience/src/build/data/com.github.GradienceTeam.Gradience.appdata.xml
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stdout:
/home/user/aur/gradience/src/build/data/com.github.GradienceTeam.Gradience.appdata.xml: FAILED:
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/colors_purple.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/colors_purple.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/colors_purple.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/colors_purple.png]
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/advanced_purple.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/advanced_purple.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/advanced_purple.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/advanced_purple.png]
• attribute-invalid     : <screenshot> width too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/monet_purple.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/monet_purple.png] maximum is 900px
• style-invalid         : <image> has vertical padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/monet_purple.png]
• style-invalid         : <image> has horizontal padding [https://raw.githubusercontent.com/GradienceTeam/Design/main/Screenshots/monet_purple.png]
stderr:
Validation of files failed
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――


Summary of Failures:

3/3 Validate appstream file FAIL            1.73s   exit status 1


```

**Comment by daudix-UFO** [comment]
Ah, looks like screenshots are too high-res (bruh)

**Comment by 0xMRTT** [comment]
@daudix-ufo Usage is done, could you review my work ?

**Comment by 0xMRTT** [comment]
Hhmm, i didn't removed the bundle, maybe a shit with git. Sorry :/

**Comment by daudix-UFO** [comment]
> Hhmm, i didn't removed the bundle, maybe a shit with git. Sorry :/

Fixed, no worries

**Comment by daudix-UFO** [comment]
BTW, GNOME Developer Documentation uses sphinx and furo theme, so we can just borrow it from there to have the tweaks applied by GNOME

**Comment by 0xMRTT** [comment]
Lol,gonna do that 😉

**Comment by 0xMRTT** [comment]
NOOOOOOOOOO

**Comment by 0xMRTT** [comment]
Why i deleted that :D :/

**Comment by 0xMRTT** [comment]
@daudix-UFO what do you think about the doc ?

**Comment by 0xMRTT** [comment]
I already added

**Comment by daudix-UFO** [comment]
изображение

**Comment by daudix-UFO** [comment]
Btw, we can continue on the `GradienceTeam/gradience-docs` branch

**Comment by 0xMRTT** [comment]
Moved the doc to GradienceTeam/docs and published on RTD at gradience.rtfd.io

**Pull request closed without merging**
