### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by tfuxu**
Update [README.md](https://github.com/GradienceTeam/Gradience/blob/main/README.md) to include updated instructions for Flatpak builds, make slight changes in formatting and add Matrix shield from [shields.io](https://shields.io) (we need to set read history to 'Anyone' in room settings in order to get that shield working).

Signed-off-by: tfuxu <73042332+tfuxu@users.noreply.github.com>

### CODE REVIEW

**Review by 0xMRTT — APPROVED** [review]

**Comment by 0xMRTT** [comment]
@daudix-UFO instead of saying "Press on three line button", i would say "Press on the menu button in the headerbar" ?

**Comment by daudix-UFO** [comment]
> @daudix-UFO instead of saying "Press on three line button", i would say "Press on the menu button in the headerbar" ?

Agree 👍

**Comment by tfuxu** [comment]
> > @daudix-UFO instead of saying "Press on three line button", i would say "Press on the menu button in the headerbar" ?
> 
> Agree +1

Also agreeing

**Comment by tfuxu** [comment]
@0xMRTT 
Don't forget to update room settings

**Pull request merged**
