### PR TITLE
A bunch of improvements

### PR DESCRIPTION
**Pull request by tfuxu**
## Changes:
- Create `buglog` function,
- Move `to_slug_case` and `buglog` to `modules/utils.py`,
- Replace print() with buglog(),
- Fix error toast showing up on startup when build in Flatpak,
- Update BUGTRACKER_URL and TRANSLATE_URL to the corrent ones,
- Add variables from meson.build to constants.py.in config,
- Show tooltip when focused on `monet_file_chooser_button`,
- Update copyright info in window.py and add in plugin_row.py,
- Update local.sh and Makefile,
- Fix typo in translator_credits,
- Add tfuxu in translator credits

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Did you checked `next` ?

**Comment by 0xMRTT** [comment]
> ## Changes:
> 
>     * Create `buglog` function,
> 
>     * Move `to_slug_case` and `buglog` to `modules/utils.py`,

Move to `__init__.py` in `next`
> 
>     * Replace print() with buglog(),
> 
>     * Fix error toast showing up on startup when build in Flatpak,
> 
>     * Update BUGTRACKER_URL and TRANSLATE_URL to the corrent ones,
> 
>     * Add variables from meson.build to constants.py.in config,
> 
>     * Show tooltip when focused on `monet_file_chooser_button`,
> 
>     * Update copyright info in window.py and add in plugin_row.py,
> 
>     * Update local.sh and Makefile,
> 
>     * Fix typo in translator_credits,
> 
>     * Add tfuxu in translator credits

Otherwise, i will review it now. Thanks again for your contribution :+1:

**Comment by tfuxu** [comment]
> > ## Changes:
> > ```
> > * Create `buglog` function,
> > 
> > * Move `to_slug_case` and `buglog` to `modules/utils.py`,
> > ```
> 
> Move to `__init__.py` in `next`
> 
> > ```
> > * Replace print() with buglog(),
> > 
> > * Fix error toast showing up on startup when build in Flatpak,
> > 
> > * Update BUGTRACKER_URL and TRANSLATE_URL to the corrent ones,
> > 
> > * Add variables from meson.build to constants.py.in config,
> > 
> > * Show tooltip when focused on `monet_file_chooser_button`,
> > 
> > * Update copyright info in window.py and add in plugin_row.py,
> > 
> > * Update local.sh and Makefile,
> > 
> > * Fix typo in translator_credits,
> > 
> > * Add tfuxu in translator credits
> > ```
> 
> Otherwise, i will review it now. Thanks again for your contribution +1

You mean to just move this PR to next?

**Comment by 0xMRTT** [comment]
> > > ## Changes:
> > > ```
> > > * Create `buglog` function,
> > > 
> > > * Move `to_slug_case` and `buglog` to `modules/utils.py`,
> > > ```
> > 
> > 
> > Move to `__init__.py` in `next`
> > > ```
> > > * Replace print() with buglog(),
> > > 
> > > * Fix error toast showing up on startup when build in Flatpak,
> > > 
> > > * Update BUGTRACKER_URL and TRANSLATE_URL to the corrent ones,
> > > 
> > > * Add variables from meson.build to constants.py.in config,
> > > 
> > > * Show tooltip when focused on `monet_file_chooser_button`,
> > > 
> > > * Update copyright info in window.py and add in plugin_row.py,
> > > 
> > > * Update local.sh and Makefile,
> > > 
> > > * Fix typo in translator_credits,
> > > 
> > > * Add tfuxu in translator credits
> > > ```
> > 
> > 
> > Otherwise, i will review it now. Thanks again for your contribution +1
> 
> You mean to just move this PR to next?

Yes 👍

**Comment by daudix-UFO** [comment]
Yes, now we make changes in `next` branch, and if everything is OK, we merge it in `main`

**Comment by tfuxu** [comment]
Ok, moved

**Comment by 0xMRTT** [comment]
And you should also modify files related to preset because they are using to_slug_case

**Comment by tfuxu** [comment]
> And you should also modify files related to preset because they are using to_slug_case

Oh okay, I didn't see that before

**Comment by 0xMRTT** [comment]
I've fully added the preset manager instead of using a dropdown

**Comment by tfuxu** [comment]
I'll just cherry pick those commits to next and reopen this PR

**Comment by 0xMRTT** [comment]
Okay, np

**Pull request closed without merging**
