### PR TITLE
Parse firefox profiles.ini files to get paths of profiles.

### PR DESCRIPTION
**Pull request by jle64**
# Parse firefox profiles.ini files to get paths of profiles

This parses firefox profiles.ini files to get the paths of the profiles instead of just treating any subdir of the firefox dir as a profile. 

This allows supporting profiles without a dot in their name which the existing glob didn't match which can happen if they are named manually, as well as profiles configured to be outside of the firefox directory that were ignored and profiles that are symlinked (by adding a resolve() on the path before the is_dir()).

There is also an additional try condition to avoid failing for the remaining profiles if encountering a profile without the customChrome.css, as it might be installed on some profiles only.

## Changelog

- Fixed theming Firefox profiles that don't have a dot in their name
- Fixed theming Firefox profiles that are outside of the Firefox dir
- Fixed theming Firefox profiles that are symlinks
- Fixed failing to theme remaining profiles after encountering one on which the firefox-gnome-theme is not present

Please note that I have only tested on non-flatpak Firefox.

### CODE REVIEW

**Review by 0xMRTT — COMMENTED** [review]
Thanks for your contribution. It's look good to me. 

@daudix-UFO what about you ?

**Comment by daudix-UFO** [comment]
@0xMRTT you know better, but it should not break anything, so LGTM!

**Review by daudix-UFO — APPROVED** [review]

**Comment by 0xMRTT** [comment]
As I can see there isn't any modifications that could result in a break for flatpak. Maybe we should test ?

**Comment by daudix-UFO** [comment]
Oki, give me a few minutes 😉

**Comment by jle64** [comment]
Just thinking about it, if someone uses absolute paths in a profile for a flatpaked firefox (with IsRelative=0 in profiles.ini), this could be an issue as absolute paths are not the same inside and outside the flatpak. But I doubt people do that in reality.

**Comment by daudix-UFO** [comment]
Likely no, I doubt someone creates additional firefox profiles than a default one.

**Review by daudix-UFO — APPROVED** [review]
Firefox via Flatpak works just fine

**Comment by daudix-UFO** [comment]
@0xMRTT merging?

**Comment by 0xMRTT** [comment]
@jle64 thanks for your contribution

**Pull request merged**
