### PR TITLE
feat: initial community presets download mechanism

### PR DESCRIPTION
**Pull request by tfuxu**
This PR adds an initial mechanism for downloading community presets using info from [presets.json](https://raw.githubusercontent.com/GradienceTeam/Community/main/presets.json) file.

In the future, there should be added some sort of fail-save procedure to prevent Gradience from crashing if perhaps Github was offline (maybe a exception handler as a dialog?).

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Could you send a screenshot of the result ?

**Comment by 0xMRTT** [comment]
image_20220824221912

I've started doing this.

**Comment by 0xMRTT** [comment]
Thanks again for your PR 🚀😎🥳

**Comment by tfuxu** [comment]
Screenshot from 2022-08-24 22-54-27

**Review by 0xMRTT — APPROVED** [review]

**Comment by 0xMRTT** [comment]
Amazing 🙂🚀. It's exactly what I wanted to do 😅😎. Thanks.

**Comment by 0xMRTT** [comment]
For the offline case, we can just add a new page to the stack which say that the computer is offlinr

**Comment by 0xMRTT** [comment]
Also, don't forget to add yourself in about dialog 👍

**Comment by tfuxu** [comment]
> Amazing slightly_smiling_facerocket. It's exactly what I wanted to do sweat_smilesunglasses.

Yea, I was faster 😅️ 

> Thanks.

No problem, if I'm using something, I'll always try to improve it

**Comment by tfuxu** [comment]
> For the offline case, we can just add a new page to the stack which say that the computer is offlinr

Yes, it can be just a [status page](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.StatusPage.html)

**Comment by 0xMRTT** [comment]
Also, if you have matrix, I suggest you to join the matrix room

**Comment by tfuxu** [comment]
> Also, if you have matrix, I suggest you to join the matrix room

ok, why not :^)

**Pull request merged**
