### PR TITLE
feat: remove libportal

### PR DESCRIPTION
**Pull request by daudix-UFO**
# Remove `libportal` from build

libportal not needed anymore as GNOME Runtime 43 already include include it

## Changelog

- Removed `libportal`

### CODE REVIEW

**Review by tfuxu — CHANGES_REQUESTED** [review]
~Please put it as a draft for now~ (I forgot that I can do this myself), we need to investigate why it still doesn't work.

**Comment by LyesSaadi** [comment]
Wild guess : Maybe it's because we don't specify libportal in meson, and since flatpak do not install the entire gnome runtime when installing an app, only what's needed for that app to function, it maybe fails to detect libportal as such and to include it in the runtime environment ?

**Comment by LyesSaadi** [comment]
Uh, it doesn't build. I think that's maybe because I put `libportal-gtk4` while I should've put a simple `libportal`. Will continue my tests tomorrow though, I need to sleep.

**Comment by daudix-UFO** [comment]
Me too, 3 AM is totally not a time for work 😉

**Comment by tfuxu** [comment]
> Uh, it doesn't build. I think that's maybe because I put `libportal-gtk4` while I should've put a simple `libportal`. Will continue my tests tomorrow though, I need to sleep.

`libportal` also doesn't seem to work.

**Comment by daudix-UFO** [comment]
Uh oh

**Comment by daudix-UFO** [comment]
Alright, as this is hard one maybe keep it for one of the future releases?

**Comment by tfuxu** [comment]
Ok, so I did some investigation, looking through [gnome-build-meta](https://gitlab.gnome.org/GNOME/gnome-build-meta) repo where manifests for building flatpak GNOME SDK and runtime are located. `libportal` is located here in [`core-deps`](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/master/elements/core-deps/libportal.bst) directory, but it looks like in order to use it, its manifest should be placed in `sdk` directory, just like [`libadwaita`](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/master/elements/sdk/libadwaita.bst) manifest. There was also a [issue](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/496) for this, but it has been closed, because `libportal` isn't yet API stable.
So, we can't remove `libportal` from our manifest, because it simply isn't yet bundled with GNOME Runtime.

**Comment by daudix-UFO** [comment]
Alright, closing then?

**Comment by tfuxu** [comment]
Probably yes.

**Pull request closed without merging**
