### PR TITLE
Create preferences window

### PR DESCRIPTION
**Pull request by tfuxu**
This PR adds a preferences window with options for setting overrides in Flatpak aplications.
These changes have, to some extent, features requested in issue https://github.com/GradienceTeam/Gradience/issues/276.

### Changes
- Create new .blp file for preferences window,
- Make `self.settings` object accessible to other files,
- Create new item in `main-menu` menu: `Preferences`

~~I'm setting this PR as a draft for now, to check if everything works as expected~~

Ps. This time, I didn't forget to update `POTFILES` :P

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Also, the ability to configure Flatpak will' go in the welcome dialog too.

**Comment by tfuxu** [comment]
> Also, the ability to configure Flatpak will' go in the welcome dialog too.

Yes, I saw that you started working on it. I could maybe move functions from `preferences.py` as a module, just so there won't be two implementations of the same feature in different parts of code.

**Comment by 0xMRTT** [comment]
Yes 👍

**Comment by tfuxu** [comment]
Okay, should be ready for review. I've also added support for gtk3 in functions, so the same functions can be used without need for creating additional changes.

**Review by 0xMRTT — APPROVED** [review]

**Pull request merged**
