### PR TITLE
Remove next branch from Devel's Flatpak manifest

### PR DESCRIPTION
**Pull request by LyesSaadi**

### CODE REVIEW

**Comment by LyesSaadi** [comment]
Created that because of #277, makes no sense to keep it if next is staying.

**Comment by LyesSaadi** [comment]
Actually, may make sense to remove it. I'm not sure the "branch" attribute does anything, and someone should be able to use Devel with any branch.

**Review by daudix-UFO — APPROVED** [review]

**Comment by 0xMRTT** [comment]
@LyesSaadi @daudix-UFO what should we do for this ?

**Comment by daudix-UFO** [comment]
Nothing? For big changes we still can use branches

**Comment by 0xMRTT** [comment]
So, close ? merge ?

**Comment by daudix-UFO** [comment]
If we will merge this, we need to change the logic of `nightly` builds, if close it, we need to create and use `next`

**Comment by daudix-UFO** [comment]
We need to do something with this

#369

**Comment by daudix-UFO** [comment]
#369 Is closed, what we should make with this?

**Pull request closed without merging**
