### PR TITLE
Update GNOME runtime to 43

### PR DESCRIPTION
**Pull request by tfuxu**
## Changes:
- update GNOME runtime to version `43`,
- add `-j4` flags for libsass and sassc to speed up compilation times,
- remove libadwaita, as version 1.2 is bundled with GNOME runtime 43,
- change "--filesystem=xdg-data/flatpak:create" to "--filesystem=xdg-data/flatpak/overrides:create" (maybe it can fix a lack of `overrides` directory in flatpak release for some users?)

### CODE REVIEW

**Comment by LyesSaadi** [comment]
Would you also like to contribute it to https://github.com/flathub/com.github.GradienceTeam.Gradience ?

(Otherwise, I'll just commit the changes on next release myself.)

**Comment by tfuxu** [comment]
> Would you also like to contribute it to https://github.com/flathub/com.github.GradienceTeam.Gradience ?
> 
> (Otherwise, I'll just commit the changes on next release myself.)

Sure, I can put that PR there too.

**Comment by LyesSaadi** [comment]
Not exactly the same json, so you'll have to adapt it a bit !

**Comment by tfuxu** [comment]
Wait, why we didn't had a `--filesystem=xdg-data/flatpak:create` flag in release json before? It was in Gradience repo way before 0.3.0
Screenshot from 2022-10-02 20-42-38

**Comment by 0xMRTT** [comment]
Hmmm

**Comment by LyesSaadi** [comment]
Oh, so that may be why some bugs happened. This seems to be an error for my part :/...

**Comment by tfuxu** [comment]
That explains a lot

**Comment by 0xMRTT** [comment]
Np 👌 another reason for releasing 0.3.1 
@daudix-UFO

**Comment by LyesSaadi** [comment]
No need, flathub releases do not need a tag update.

**Comment by daudix-UFO** [comment]
This update features some changes so small release notes and tag would be good to have

**Comment by LyesSaadi** [comment]
Yup, but this is a package bug, not a Gradience bug. It would be more beneficial to push this ASAP.

**Comment by LyesSaadi** [comment]
Also, @tfuxu, Gradience's flatpak and the Flathub flatpak aren't synced. I do some changes to the flatpak manifest to remove unnecessary double build of python-lxml for example. And both shouldn't be synced IMO.

**Comment by daudix-UFO** [comment]
👍

**Comment by tfuxu** [comment]
> Also, @tfuxu, Gradience's flatpak and the Flathub flatpak aren't synced. I do some changes to the flatpak manifest to remove unnecessary double build of python-lxml for example. And both shouldn't be synced IMO, since some specific changes not wanted for release may be applied to the repo flatpak manifest.

Okay, I'm putting my PR as a draft until a release, so you'll be able to audit my changes.

**Comment by LyesSaadi** [comment]
> > Also, @tfuxu, Gradience's flatpak and the Flathub flatpak aren't synced. I do some changes to the flatpak manifest to remove unnecessary double build of python-lxml for example. And both shouldn't be synced IMO, since some specific changes not wanted for release may be applied to the repo flatpak manifest.
> 
> Okay, I'm putting my PR as a draft until a release, so you'll be able to audit my changes.

It's not needed for it to be a draft !

**Comment by tfuxu** [comment]
Oh, okay

**Pull request merged**
