### PR TITLE
feat: Remove not very useful welcome pages

### PR DESCRIPTION
**Pull request by daudix-UFO**
## Description

Removes a bunch of code that took time and effort to write, for sake of shorter welcome screen experience

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Removed
  - Setup, progress and done pages

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

No information provided.

### CODE REVIEW

**Comment by 0xMRTT** [comment]
@daudix-UFO fixed the agree button. This should work as expected now!

**Comment by daudix-UFO** [comment]
Great, thanks bud!

**Comment by 0xMRTT** [comment]
So can we merge or not ?

**Comment by daudix-UFO** [comment]
If it all works then yea :)

**Pull request merged**
