### PR TITLE
Review Chinese Simplified translate

### PR DESCRIPTION
**Pull request by yangyangdaji**
Review Chinese Simplified translate

Signed-off-by: yangyangdaji <1504305527@qq.com>

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Maybe u already know that but if you want, you can use weblate.

**Review by 0xMRTT — APPROVED** [review]

**Comment by yangyangdaji** [comment]
Screenshot_20221008_064001
As the translation has been approved. I cannot change the translation at Weblate.

**Comment by 0xMRTT** [comment]
Oh :/

**Comment by yangyangdaji** [comment]
I have suggested to them，see https://github.com/WeblateOrg/weblate/issues/8196

**Comment by yangyangdaji** [comment]
@0xMRTT 

According to [Weblate Documentation](https://docs.weblate.org/en/latest/workflows.html#translation-states)

> Approved

> Translation has been approved in the review. It can no longer be changed by translators, but only by reviewers. Translators can only add suggestions to it.
This state is only available when reviews are enabled.

So to edit at any time without approval

**Comment by 0xMRTT** [comment]
Oh 😳

**Pull request merged**
