### PR TITLE
Updated French Translation

### PR DESCRIPTION
**Pull request by rene-coty**
I updated the fr.po file + corrected some errors on some translated strings

### CODE REVIEW

**Review by AdwCustomizer — COMMENTED** [review]
Welcome on Gradience. 🥳 We really appreciate your pull request. The core team will review your issue as soon as possible.

**Comment by 0xMRTT** [comment]
Thanks :+1:

**Comment by 0xMRTT** [comment]
I've only did a rapid translation in French, without special things like `'`. 

If you want, you can use weblate.

**Comment by 0xMRTT** [comment]
@all-contributors please add @rene-coty  for translation

**Pull request merged**
