### PR TITLE
feat: use jsdeliver instead of github url

### PR DESCRIPTION
**Pull request by 0xMRTT**
# Description

We can use [JSDeliver](https://www.jsdelivr.com/features) for downloading files instead of directly getting them from github because:
- CDN all around the world (more than 750 point of presence) and in China
- based on multiple providers 
- almost 100% uptime 
- files are stored in a permanent S3 storage to ensure that files remain avaiilble even if **Github goes down**.

# Blocking

- [ ] Maybe, that can lead to slow propagation of preset if we do changes

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Changed repo url

## Testing

- [x] I have tested my changes and verified that they work as expected

### CODE REVIEW

**Comment by tfuxu** [comment]
Maybe we should inform users about using JSDeliver service? I don't think we need to do this in-app, but a small note section in readme would be good to add.

**Comment by daudix-UFO** [comment]
maybe this is over-kill for our app?

**Comment by 0xMRTT** [comment]
That can help to provide preset everytime, even if github goes down ...

**Comment by daudix-UFO** [comment]
Gradience is not life-supporting machine, if github goes down it's not such a big deal imo, instead we can implement caching, presets are small in size so it will be not storage hungry

**Comment by tfuxu** [comment]
Converting to draft, as we need to add preferences option for this PR.

**Comment by tfuxu** [comment]
Why?

**Comment by 0xMRTT** [comment]
I think that's not necessary ...

**Comment by tfuxu** [comment]
It isn't necessary, but it still would be useful if Github for example went down

**Comment by 0xMRTT** [comment]
yep that's true and maybe we can also try to use codeberg if github is down

**Comment by 0xMRTT** [comment]
@daudix-UFO RFC for title and subtitle

@tfuxu Request for code review

**Comment by daudix-UFO** [comment]
First issue, can't start

```
Приложение запущено в 22:02:26
                              Traceback (most recent call last):
  File "/app/bin/gradience", line 70, in <module>
    from gradience.frontend import main
  File "/app/lib/python3.10/site-packages/gradience/frontend/main.py", line 27, in <module>
    from gradience.backend.globals import presets_dir, get_gtk_theme_dir
  File "/app/lib/python3.10/site-packages/gradience/backend/globals.py", line 53, in <module>
    preset_repos = preset_repos_github
NameError: name 'preset_repos_github' is not defined
Приложение завершилось
```

**Comment by 0xMRTT** [comment]
Oh messed up when resolving the merge conflict 🤫

**Review by daudix-UFO — APPROVED** [review]

**Comment by tfuxu** [comment]
I'll review the code tomorrow, as it's pretty late where I live, but from what I quickly tested, it looks and works fine

**Review by tfuxu — APPROVED** [review]
Works for me after a fix. I'd like to re-request @0xMRTT and @daudix-UFO for review to make sure it works properly on your machines too.

**Review by daudix-UFO — APPROVED** [review]
Works fine :)

**Comment by 0xMRTT** [comment]
Hmm, I think that there is one preset repos which is still using the hardcoded one but idk where it is since I'm not at home...

**Comment by daudix-UFO** [comment]
JSDeliver is used for both official and curated, so I think it's fine

image

**Comment by 0xMRTT** [comment]
Tried, and that's okay for me!

**Pull request merged**
