### PR TITLE
Implement backup functionality for gtk.css

### PR DESCRIPTION
**Pull request by DivineBicycle**
Instead of just overwriting `gtk.css` with a new `gtk.css` when applying the theme, we write the current contents of `gtk.css` to `gtk.css.bak` then write apply our changes to `gtk.css`

### CODE REVIEW

**Comment by DivineBicycle** [comment]
I'm trying to implement the restore functionality now, it's taking a bit longer than expected.

**Comment by DivineBicycle** [comment]
If you check `main.py`, you will see how far I have gotten. It hasn't been fully done, because I am getting the following error when trying to click the restore button. I tried moving the method from where it originially was, above the `reset_color_scheme` method to above the `show_restore_color_scheme_dialog` method but still no luck.

`
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gradience/main.py", line 445, in show_restore_color_scheme_dialog
    dialog.connect("response", self.restore_color_scheme)
`

**Comment by 0xMRTT** [comment]
Could you show the full traceback?

Currently, the management of presets is very basic. Having the ability to restore, backup would be great 👍.

**Comment by 0xMRTT** [comment]
Also for the style, please use 4spaces or 1 tab (there is a lot of style change in your PR

**Comment by DivineBicycle** [comment]
```
Application started at 15:22:18
DEBUG:root:disabled plugins: []
DEBUG:root:{}
DEBUG:root:file:///usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:adwaita-d.jpg
DEBUG:root:/usr/share/backgrounds/gnome/adwaita-d.jpg
DEBUG:root:normal run

(gradience:2): Gtk-CRITICAL **: 15:22:18.810: Unable to connect to the accessibility bus at 'unix:path=/run/user/1002/at-spi/bus_1,guid=23a786a36d77540ceea05ff0630e9d19': Could not connect: No such file or directory
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/gradience/main.py", line 445, in show_restore_color_scheme_dialog
    dialog.connect("response", self.restore_color_scheme)
AttributeError: 'GradienceApplication' object has no attribute 'restore_color_scheme'
```

**Comment by 0xMRTT** [comment]
See #302 and #303 for style

**Comment by 0xMRTT** [comment]
Also, I suggest to join the matrix room or the discord server (they are bridged)

https://discord.gg/rwNDGPJf

Link to the matrix room on the README

**Comment by DivineBicycle** [comment]
Oops

**Comment by DivineBicycle** [comment]
I still haven't been able to get that code to work. Am I missing some weird thing in GTK?

**Comment by 0xMRTT** [comment]
Same error ?

**Comment by DivineBicycle** [comment]
> Same error ?

yea, and I can't get it to build *again*

**Review by tfuxu — CHANGES_REQUESTED** [review]
This formatting across whole `main.py` is very confusing, as it's hard to even see what changes you've added. You should start with a clean file, put changes related to PR in it, and maybe add formatting in another commit.

**Comment by DivineBicycle** [comment]
> This formatting across whole `main.py` is very confusing, as it's hard to even see what changes you've added. You should start again with a clean file, put changes related to PR in it, and maybe add formatting in another commit.

Yup, I kept on getting inconsistent uses of spaces and tabs for indentation errors since I was stupidly trying to do actual development work with builder so I converted the whole file to tabs using Pycharm. I'll take the methods out and put them back in then push again.

**Pull request merged**
