### PR TITLE
Backport new Theming page and `theming/preset` module changes

### PR DESCRIPTION
**Pull request by tfuxu**
## Description

This PR backports new Theming page and various changes in `theming/preset` module and other related modules.

## Type of change

- [ ] Bugfix (Change which fixes a issue)
- [x] New feature (Change which adds new functionality)
- [ ] Enhancement (Change which slightly improves existing code)
- [x] Backport (Changes from non-upstream branch ported to upstream)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Backport new structure of Theming Page and new preferences window
- Split Theme Engines groups into individual modules
- Refactor `preset` model class
- Backport `color_vars_to_color_code` function

## Testing

- [x] I have tested my changes and verified that they work as expected 

#### Tested on:
- Local build
- Flatpak package

### How to test the changes

Test only GUI part, CLI can be left untested, as there wasn't any major changes in it.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Is this switch intended to be grayed out in on-off mix state?

**Comment by tfuxu** [comment]
Yes, because we don't have yet a fallback page for Theming tab for when every Theme Engine is disabled, but I'll make it available again before 0.8.0 release.

**Comment by tfuxu** [comment]
Ah yes, kinda weird, but it looks normal on my machine, so idk what can be causing that.

**Comment by daudix-UFO** [comment]
Okay then, probably something on my end :P

**Comment by 0xMRTT** [comment]
image
same issue :D

**Comment by tfuxu** [comment]
Yeah too actually, but in Blur my Shell prefs instead :P
Screenshot from 2023-03-12 16-27-36

**Comment by tfuxu** [comment]
Closing, as #679 is almost completed and it will contain some fixes which aren't included here.

**Pull request closed without merging**
