### PR TITLE
Theming rework

### PR DESCRIPTION
**Pull request by 0xMRTT**
To-Do:

- [ ] ~~Create an extension that follow desktop changes~~ we will do a service instead
	- [x] ~~Create the repo~~
	- [x] ~~Setup the ext~~
	- [ ] ~~Follow light/dark switch~~
	- [ ] ~~Follow background switch~~
	- [ ] ~~Nice to have~~
		- [ ] ~~Add translation~~
		- [ ] ~~Publish to the AUR~~
		- [ ] ~~Automatically download in welcome setup~~
- [ ] ~~Add CLI to Gradience~~ Ported to upstream
	- [ ] ~~Add `change-theme`~~
	- [x] ~~Add `apply <preset-path>`~~
	- [x] ~~Add `monet <background>`~~
	- [ ] ~~Add `port <old-preset --theme light|dark>`~~
	- [ ] ~~Translate CLI~~
- [ ] ~~Separate frontend from backend~~ Ported to upstream
	- [x] ~~Move monet generation to the backend~~
	- [x] ~~Move preset management to the backend~~
	- [ ] ~~Move plugin management to the backend~~
- [ ] Add button in the header bar for switching between light and dark
	- [ ] Color mode switcher icon
- [ ] use new preset class
- [ ] Improve apply and save dialog
	- [ ] Use a similar design as in other gnome apps
- [ ] ~~Add GNOME Shell theming~~ Currently being ported to upstream
	- [ ] ~~Add UI in Gradience~~
		- [ ] ~~Customization list~~
	- [x] ~~Add generation in `theme.py`~~
- [ ] Add port dialog

### CODE REVIEW

**Comment by 0xMRTT** [comment]
@daudix-UFO 

image

**Comment by 0xMRTT** [comment]
@daudix-UFO have a look to `gradience/modules/preset.py`. It will be how the dark/light preset will work:

``` json
{
  "name": "An Amazing Name",
  ... 
  "light": {
	"variables": {
       ... light vars
    },
   	"palette": {
     	... light palette
    }
  },
  "dark": {
    "variables": {
       ... dark vars
    },
   	"palette": {
     	... dark palette
    }
  },
  # and we can also add (the python class is now more flexible)
  "variants": {
     "dark": {
        "red": {
           ... red variant
        }
     }
  }
  "default": "light" 
  # by default it's light. When the preset will be loaded, gradience will choose light or dark view by default.
}
```

Since that will break the current preset format. I'll also provide a `port` tool.

**Comment by daudix-UFO** [comment]
Very nice!

**Comment by 0xMRTT** [comment]
Do you agree on the idea ?

**Comment by daudix-UFO** [comment]
> Do you agree on the idea ?

Yes 👍

**Comment by tfuxu** [comment]
Regarding the last checkpoint in a to-do list, we shouldn't move modules from `utils/`, because this will make the codebase less flexible to contribute into. Why would a potential contributor, who wants to contribute to both the frontend and backend, have to clone both repositories just to get a functional program?

**Comment by 0xMRTT** [comment]
By seprating backend from frontend, i wouuld like to make something similar to the Bottles architecture

**Comment by tfuxu** [comment]
Sure, we could do that, but not as a separate library.

**Comment by daudix-UFO** [comment]
Yep, bottles just have separate folders in project

**Comment by tfuxu** [comment]
I can't get Gradience to work with commits in this PR. I was fixing merge conflicts, and when I tried to run Gradience I've got this error:
```
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 138, in do_activate
    self.load_preset_from_css()
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 298, in load_preset_from_css
    self.load_preset_from_resource(
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 329, in load_preset_from_resource
    preset_text = Gio.resources_lookup_data(
gi.repository.GLib.GError: g-resource-error-quark: The resource at “/com/github/GradienceTeam/Gradience/presets/adwaita-dark.json” does not exist (0)
```
I've figured out that because theme format has changed, we no longer need `adwaita-dark`, but after commenting out this [lines](https://github.com/GradienceTeam/Gradience/blob/theme-rework/gradience/main.py#L296-L299), I'm now getting this error:
```
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 138, in do_activate
    self.load_preset_from_css()
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 301, in load_preset_from_css
    self.load_preset_from_resource(
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/gradience/main.py", line 331, in load_preset_from_resource
    self.preset = Preset(text=preset_text)
TypeError: Preset.__init__() got an unexpected keyword argument 'text'
```

**Comment by 0xMRTT** [comment]
That's normal, the changement in the `Preset` class broke everything

**Comment by tfuxu** [comment]
You should convert subprojects to submodules, and I think that a perfect place for them will be in `data/` folder

**Comment by 0xMRTT** [comment]
How do u do that ?

**Comment by tfuxu** [comment]
Check out this: https://www.atlassian.com/git/tutorials/git-submodule
I've seen that you changed some meson files in those subprojects, so in that case, you could create a new repository just for submodules, like the one flathub org has: https://github.com/flathub/shared-modules

**Comment by tfuxu** [comment]
@0xMRTT 
I fixed merge conflicts for this PR, but before I'll put a fix here, please check if I didn't mess anything up: https://github.com/tfuxu/AdwCustomizer/tree/theme-rework

**Comment by 0xMRTT** [comment]
@tfuxu i think that we can split the PR and move the CLI to a new one since it's almost done

**Comment by daudix-UFO** [comment]
Can this branch be deleted?

**Comment by 0xMRTT** [comment]
We can keep it as an archive ...

**Pull request closed without merging**
