### PR TITLE
Refactor shell theming module

### PR DESCRIPTION
**Pull request by lavafroth**
## Description

This PR refactors a few operations to make the code handle edge cases efficiently with marginal performance improvements.

## Type of change

- [ ] Bugfix (Change which fixes an issue)
- [ ] New feature (Change which adds new functionality)
- [x] Enhancement (Change which slightly improves existing code)
- [ ] Breaking change (This change will introduce incompatibility with existing functionality)

## Changelog 

- Stores the comma separated string representation of valid versions for later use in raising exceptions.
- Uses tuple for `async_data` in `ShellTheme` since its members are immutable.
- Uses tuple decomposition to assign theme variant and preset from `async_data` later.
- Replaces `Gio.File.make_directory_with_parents` with Python's builtin `os.makedirs` with `exist_ok` as True to implicitly create directories when nonexistent.
-  Instead of relying on `KeyError`s when accessing dictionary values, the `get` method is used to supply a default value.
- When a key might exist in one dictionary, the `get` method (which may return `None`) is coupled with the nullish `or` operator to use the value that is not `None`.
- Uses predefined `main_source` attribute as argument to the `_compile_sass` function.
- Uses the walrus operator to scope a template match to the condition when it is not `None`.
- Removes unnecessary implicit `.close()`s on file handles when using context managers.

## Testing

- [x] I have tested my changes and verified that they work as expected 

### How to test the changes

Just run `./local.sh`

### CODE REVIEW

**Review by tfuxu — COMMENTED** [review]
Thanks for this refactoring job @lavafroth! Overall looks good, but I'll do a proper review tomorrow

**Review by tfuxu — APPROVED** [review]
Alright, I've tested everything related to this refactor and it works flawlessly. 

Thanks again for this refactor, I didn't thought anyone would be able to decipher this mess I wrote here 😅️

**Comment by tfuxu** [comment]
@0xMRTT Any objections, or can we merge this?

**Comment by 0xMRTT** [comment]
LGTM We can merge ! Thanks for clearing the mess lol

**Pull request merged**
